### ISSUE TITLE
TBC 2.4.3. Backport?

### ISSUE THREAD

**Issue by Maggew** [larsnorbergofficial/DiabolicUI#1]
What kind of investment of time do you think would be required to get this compatible?

**Comment by larsnorbergofficial** [comment]
I have no idea. I didn't make addons back then, and core components like how to make actionbars and unitframes were very different. 

I do however plan to download a TBC client and take a look. If it's doable to backport (without going crazy in the process) I'll do it. :) 

I have no ETA, though. Currently on vacation, and will be back infront of my computer in 4 days. So we'll see then. :)

**Comment by Maggew** [comment]
Win Client Download
https://mega.nz/#!VsMhkJYA!1IMFcWxvILz7eXzHcyp_R9Lb7SSOCgcRE_qfdoHPHZg

Forum Account Creation
http://looking4group.eu/hellfire/member.php?action=register

Ingame Account Creation
http://looking4group.eu/accreg_old/

Here is a nice list of wowservers too
https://www.reddit.com/r/wowservers/comments/37b5ir/wow_private_servers_list/

Well I really hope the backport isn't to crazy. I hope you had a great vacation in Poland!

**Comment by Maggew** [comment]
Any status on Vanilla or TBC?
